packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@scarf/scarf': false
  '@stellar/stellar-sdk': true
  bigint-buffer: true
  blake-hash: true
  bufferutil: true
  keccak: true
  protobufjs: true
  sharp: true
  tiny-secp256k1: true
  unrs-resolver: true
  usb: false
  utf-8-validate: true
